apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-project-deployment
  labels:
    app: kube-project
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: kube-project
  template:
    metadata:
      labels:
        app: kube-project
    spec:
      containers:
      - name: kube-project-container
        image: briitznewacr.azurecr.io/${IMAGE_NAME}:${IMAGE_TAG}
 
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
