name: Kubernetes Pipeline

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      Image_Name: olawale
      Image_Tag: ${{ github.sha }}

    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3


    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}



    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f project/Dockerfile project/


    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}


    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: Set Kubernetes context
      uses: azure/aks-set-context@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: myCluster
        resource-group: myResourceGroup


    - name: Deploy to AKS
      run: |
        kubectl apply -f project/k8s/deployment.yaml 
        kubectl apply -f project/k8s/service.yaml
        kubectl rollout status deployment/kube-project-deployment
